menu:
  Home: /
  Archives: /archives
  About: /about
  RSS: /atom.xml

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: minglq
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss:

# comment_provider: facebook
# Facebook comment
# facebook:
  # appid: 123456789012345
  # comment_count: 5
  # comment_width: 840
  # comment_colorscheme: light

